#INCLUDED DEMOS
# 1. Custom Text Classification
# 2. Custom Named Entity Recognition

@api-version=2022-05-01
@endpoint=https://languageunaicustomclassify.cognitiveservices.azure.com

### 1. Custom Text Classification

#previously trained using Language Studio

@text1= "Celebrities come out for the big awards ceremony.The stars of television and cinema were out in force on Thursday night for the first awards event of the season. The Contoso Awards celebrate artistic achievements in TV and file, and highlight the emerging stars we love to watch!"
@text2="League best, worst XIs: Man United stars Pogba, Maguire had season to forget; Kane, Son shone for Spurs.After a final day of maximum drama, the glittering prizes in the League are decided: Real Contoso champions for the fourth time in five years, London foiled in a photo finish, Fabrikam in the League and Adatum United marching on into another season in the top flight.But how about the individual accolades? And how about those who would probably prefer to forget the season? Everyone will have their own ideas about the real movers and shakers, so without further ado, here are this observer's best and worst teams of 2021-22."
@projectName="ClassifyLab"
@deploymentName="staging"

# @name classify_start
POST {{endpoint}}/language/analyze-text/jobs?api-version={{api-version}}
Content-Type: application/json
Ocp-Apim-Subscription-Key: {{$processEnv LANGUAGEAI_KEY}}

{
  "displayName": "Classifying documents",
  "analysisInput": {
    "documents": [
      {
        "id": "1",
        "language": "en",
        "text": {{text1}}
      },
      {
        "id": "2",
        "language": "en",
        "text": {{text2}}
      }
    ]
  },
  "tasks": [
    {
      "kind": "CustomSingleLabelClassification",
      "taskName": "Single Classification Label",
      "parameters": {
        "projectName": {{projectName}},
        "deploymentName": {{deploymentName}}
      }
    }
  ]
}

### @name get-classify
@request={{classify_start.response.headers.operation-location}}

GET {{request}}
Content-Type: application/json
Ocp-Apim-Subscription-Key: {{$processEnv LANGUAGEAI_KEY}}

### 2. Custom Named Entity Recognition

#previously trained using Language Studio

@text1= "Bluetooth earbuds, $100. These work okay, but sometimes disconnect from the phone. I'm sure someone more technical that me could figure it out.Located in Sacramento, CA"
@text2="Ad Title: Amazing Deal! Ad Description: Don't miss out on this amazing deal! We're selling a brand new laptop for only $999 in New York City. The laptop is packed with powerful features and is perfect for both work and play. Contact us now to get your hands on this incredible offer!"
@projectName="CustomEntityLab"
@deploymentName="AdEntities"

# @name entity_start
POST {{endpoint}}/language/analyze-text/jobs?api-version={{api-version}}
Content-Type: application/json
Ocp-Apim-Subscription-Key: {{$processEnv LANGUAGEAI_KEY}}

{
  "displayName": "Extracting entities",
  "analysisInput": {
    "documents": [
      {
        "id": "1",
        "language": "en",
        "text": {{text1}}
      },
      {
        "id": "2",
        "language": "en",
        "text": {{text2}}
      }
    ]
  },
  "tasks": [
     {
      "kind": "CustomEntityRecognition",
      "taskName": "Entity Recognition",
      "parameters": {
        "projectName": {{projectName}},
        "deploymentName": {{deploymentName}}
      }
    }
  ]
}

### @name get-entity
@request={{entity_start.response.headers.operation-location}}

GET {{request}}
Content-Type: application/json
Ocp-Apim-Subscription-Key: {{$processEnv LANGUAGEAI_KEY}}
