## Testing Vision AI 4.0 custom classify model

## REFERENCE https://learn.microsoft.com/en-us/azure/ai-services/computer-vision/how-to/call-analyze-image-40?pivots=programming-language-rest-api

### NOTE request history shows command with the used variables!
@Endpoint={{$processEnv AIVISION_AI102_ENDPOINT}}

-----------------

### VERSION 4 
#custom model name
@model-name=classifyfruit

@language=en
@api-version=2023-02-01-preview

@imageUrl="https://th.bing.com/th/id/OIP.Wyv-wg2NQMzDlyrAPBfmqgHaHU?rs=1&pid=ImgDetMain"


POST {{Endpoint}}/computervision/imageanalysis:analyze?api-version={{api-version}}&model-name={{model-name}}
Content-Type: application/json
Ocp-Apim-Subscription-Key: {{$processEnv AIVISION_AI102_KEY}}

{
  "url": {{imageUrl}}
}
