# REFERENCE DOC https://westus.dev.cognitive.microsoft.com/docs/services/563879b61984550e40cbbe8d/operations/563879b61984550f30395236

#INCLUDED DEMOS
# 1. Detect - FaceID and Face Attributes
# 2. Verify - FaceID and FaceID
# 3. Identify - FaceID vs PersonGroup
  # Training done in the other file! 


# IMAGES USED
# 1. MIKEL OYARZABAL
  # https://img.a.transfermarkt.technology/portrait/big/351478-1599987229.jpg?lm=1
  # https://s.hs-data.com/bilder/spieler/gross/290844.jpg
# 2. MARTIN ZUBIMENDI
  # https://th.bing.com/th/id/OIP.jbMJjsG79JtkzUhotoOnmAHaIC?rs=1&pid=ImgDetMain
  # https://th.bing.com/th/id/R.1e8ba36e99def5f9db9e25b946f3f089?rik=LbRv%2bU38Qya5RA&pid=ImgRaw&r=0
# 3. SATYA NADELLA  https://th.bing.com/th/id/OIP.Ue_cLPMfXZoug1uixdW_iwHaFj?rs=1&pid=ImgDetMain

# Service Principal credentials
@tenantId={{$processEnv AZURE_TENANT_ID}}
@clientId={{$processEnv AZURE_CLIENT_ID}}
@clientSecret={{$processEnv AZURE_CLIENT_SECRET}}

### 0. Get Bearer Token using Service Principal
# @name getToken
POST https://login.microsoftonline.com/{{tenantId}}/oauth2/v2.0/token
Content-Type: application/x-www-form-urlencoded

client_id={{clientId}}&client_secret={{clientSecret}}&scope=https://cognitiveservices.azure.com/.default&grant_type=client_credentials


### NOTE request history shows command with the used variables!
@Endpoint={{$processEnv AIFACE_END}}

-----------------

### Detect - FaceID and Face Attributes

@returnFaceId=true
@returnFaceLandmarks=true
@returnFaceAttributes=accessories,blur,exposure,glasses,headpose,noise, qualityForRecognition

@recognitionModel=recognition_04
# default 24 hours (60s to 86400s)
@faceIdTimeToLive = 86400 

@imageUrl="https://tse2.mm.bing.net/th/id/OIP.ueTQHh8NCwgRbMy6suwB0wHaEK?rs=1&pid=ImgDetMain&o=7&rm=3"

POST {{Endpoint}}/face/v1.0/detect?returnFaceId={{returnFaceId}}&returnFaceLandmarks={{returnFaceLandmarks}}&returnFaceAttributes={{returnFaceAttributes}}&faceIdTimeToLive={{faceIdTimeToLive}}&recognitionModel={{recognitionModel}}
Content-Type: application/json
Authorization: Bearer {{getToken.response.body.access_token}}

{
  "url": {{imageUrl}}
}


### Verify - FaceID and FaceID

@faceId1="da5a5a4f-1407-42e7-adfa-9c8bcd3b837f"
@faceId2="b3b22e88-bf33-4f98-99e9-211c358d430f"


POST {{Endpoint}}/face/v1.0/verify?
Content-Type: application/json
Authorization: Bearer {{getToken.response.body.access_token}}

{
  "faceId1": {{faceId1}},
  "faceId2": {{faceId2}}
}

### Identify - FaceID and PersonGroup

#get one calling detect
@faceId="da5a5a4f-1407-42e7-adfa-9c8bcd3b837f"
@personGroupId=real-sociedad


POST {{Endpoint}}/face/v1.0/identify?
Content-Type: application/json
Authorization: Bearer {{getToken.response.body.access_token}}

{
  "faceIds": [{{faceId}}],
  "personGroupId": "{{personGroupId}}"
}

# MIKEL OYARZABAL - d7ffecf9-8170-48f8-a6e2-5ba8a0af907b

