# REFERENCE DOC https://westus.dev.cognitive.microsoft.com/docs/services/563879b61984550e40cbbe8d/operations/563879b61984550f30395236

#INCLUDED DEMOS
# 1. Detect - FaceID and Face Attributes
# 2. Verify - FaceID and FaceID
# 3. Identify - FaceID vs PersonGroup
  # Training done in the other file! 


# IMAGES USED
# 1. MIKEL OYARZABAL
  # https://img.a.transfermarkt.technology/portrait/big/351478-1599987229.jpg?lm=1
  # https://s.hs-data.com/bilder/spieler/gross/290844.jpg
# 2. MARTIN ZUBIMENDI
  # https://th.bing.com/th/id/OIP.jbMJjsG79JtkzUhotoOnmAHaIC?rs=1&pid=ImgDetMain
  # https://th.bing.com/th/id/R.1e8ba36e99def5f9db9e25b946f3f089?rik=LbRv%2bU38Qya5RA&pid=ImgRaw&r=0
# 3. SATYA NADELLA  https://th.bing.com/th/id/OIP.Ue_cLPMfXZoug1uixdW_iwHaFj?rs=1&pid=ImgDetMain


### NOTE request history shows command with the used variables!
@Endpoint={{$processEnv AIFACE_END}}

-----------------

### Detect - FaceID and Face Attributes

@returnFaceId=true
@returnFaceLandmarks=true
@returnFaceAttributes=accessories,blur,exposure,glasses,headpose,noise, qualityForRecognition

@recognitionModel=recognition_04
# default 24 hours (60s to 86400s)
@faceIdTimeToLive = 86400 

@imageUrl="https://icdn.football-espana.net/wp-content/uploads/2023/11/OYARZABAL-2.jpeg"

POST {{Endpoint}}/face/v1.0/detect?returnFaceId={{returnFaceId}}&returnFaceLandmarks={{returnFaceLandmarks}}&returnFaceAttributes={{returnFaceAttributes}}&faceIdTimeToLive={{faceIdTimeToLive}}&recognitionModel={{recognitionModel}}
Content-Type: application/json
Ocp-Apim-Subscription-Key: {{$processEnv AIFACE_SECRET}}

{
  "url": {{imageUrl}}
}


### Verify - FaceID and FaceID

@faceId1="8597a031-66a8-4eb2-8203-0d29d2599361"
@faceId2="88ec2c6b-2dc7-4466-b09e-d5d4e288388f"


POST {{Endpoint}}/face/v1.0/verify?
Content-Type: application/json
Ocp-Apim-Subscription-Key: {{$processEnv AIFACE_SECRET}}

{
  "faceId1": {{faceId1}},
  "faceId2": {{faceId2}}
}

### Identify - FaceID and PersonGroup

#get one calling detect
@faceId="8597a031-66a8-4eb2-8203-0d29d2599361"
@personGroupId=real-sociedad


POST {{Endpoint}}/face/v1.0/identify?
Content-Type: application/json
Ocp-Apim-Subscription-Key: {{$processEnv AIFACE_SECRET}}

{
  "faceIds": [{{faceId}}],
  "personGroupId": "{{personGroupId}}"
}

# MIKEL OYARZABAL - 5dba1ea2-e706-4f13-8e1e-e838689003d5
# MARTIN ZUBIMENDI - ba9cb60d-8ff7-49e1-b037-c6a4ab80b3ad
