### 2. Custom Named Entity Recognition
@api-version=2022-05-01
@endpoint=https://languageunaicustomclassify.cognitiveservices.azure.com

#previously trained using Language Studio

@text1= "Bluetooth earbuds, $100. These work okay, but sometimes disconnect from the phone. I'm sure someone more technical that me could figure it out.Located in Sacramento, CA"
@text2="Ad Title: Amazing Deal! Ad Description: Don't miss out on this amazing deal! We're selling a brand new laptop for only $999 in New York City. The laptop is packed with powerful features and is perfect for both work and play. Contact us now to get your hands on this incredible offer!"
@projectName="CustomEntityLab"
@deploymentName="AdEntities"

# @name entity_start
POST {{endpoint}}/language/analyze-text/jobs?api-version={{api-version}}
Content-Type: application/json
Ocp-Apim-Subscription-Key: {{$processEnv LANGUAGEAI_KEY}}

{
  "displayName": "Extracting entities",
  "analysisInput": {
    "documents": [
      {
        "id": "1",
        "language": "en",
        "text": {{text1}}
      },
      {
        "id": "2",
        "language": "en",
        "text": {{text2}}
      }
    ]
  },
  "tasks": [
     {
      "kind": "CustomEntityRecognition",
      "taskName": "Entity Recognition",
      "parameters": {
        "projectName": {{projectName}},
        "deploymentName": {{deploymentName}}
      }
    }
  ]
}

### @name get-entity
@request={{entity_start.response.headers.operation-location}}

GET {{request}}
Content-Type: application/json
Ocp-Apim-Subscription-Key: {{$processEnv LANGUAGEAI_KEY}}