
### CREATE DATASET IN AZURE VISION API
@endpoint=https://ai102computervisionunai.cognitiveservices.azure.com/
@dataset-name=training-data-fruit
@annotationFileUri=https://ai102cvcustomnewv4.blob.core.windows.net/fruit/training_labels.json

PUT {{endpoint}}/computervision/datasets/{{dataset-name}}?api-version=2023-02-01-preview
Content-Type: application/json
Ocp-Apim-Subscription-Key: {{$processEnv AIVISION_AI102_KEY}}

{
'annotationKind':'imageClassification',
'annotationFileUris':['{{annotationFileUri}}']
}"