### DEMOS for ChatCompletion API
# https://learn.microsoft.com/en-us/azure/ai-services/openai/reference 

#DEMOS included
# 1. Get simple completion
# 2. Using system message
# 3. Using system message + few shot learning

#replace with your values 
@endpoint=https://ai-050-swedencentral-previews.openai.azure.com/
@deploymentName=gpt-4-unai

@api-version=2024-02-01

### 1. Get simple completion
POST  {{endpoint}}/openai/deployments/{{deploymentName}}/chat/completions?api-version={{api-version}}
Content-Type: application/json
api-key: {{$processEnv AOAI_SWEDEN_KEY}}

{
  "messages": [
        {
        "role": "system",
        "content": "You are an AI assistant that helps people find information."
        },
        {
        "role": "user",
        "content": "What is the capital of Sweden?"
        }
    ],
    "max_tokens": 50
}

### 2. Using system message
POST  {{endpoint}}/openai/deployments/{{deploymentName}}/chat/completions?api-version={{api-version}}
Content-Type: application/json
api-key: {{$processEnv AOAI_SWEDEN_KEY}}

{
  "messages": [
        {
        "role": "system",
        "content": "Just reply with the capital and population"
        },
        {
        "role": "user",
        "content": "What is the capital of Sweden?"
        }
    ],
    "max_tokens": 50
}

### 2. Using system message + few shot learning
POST  {{endpoint}}/openai/deployments/{{deploymentName}}/chat/completions?api-version={{api-version}}
Content-Type: application/json
api-key: {{$processEnv AOAI_SWEDEN_KEY}}

{
  "messages": [
        {
            "role": "system",
            "content": "Just reply with the capital and population"
        },
        {
            "role": "user",
            "content": "What is the capital of Sweden?"
        },
        {
            "role": "assistant",
            "content": "City=Stockholm \n Population=10 million "
        },
        {
            "role": "user",
            "content": "What is the capital of France?"
        }

    ],
    "max_tokens": 50
}

